/* DO NOT EDIT: This file is auto-generated and will be overwritten. [build-fingerprint:codegen] */
export const style = {
  "--megamenu-chrome-height": "--tvg_header_BIfLoG_megamenu-chrome-height",
  "actions": "tvg_header_BIfLoG_actions",
  "actions__icon": "tvg_header_BIfLoG_actions__icon",
  "actions__icon--account": "tvg_header_BIfLoG_actions__icon--account",
  "actions__icon--search": "tvg_header_BIfLoG_actions__icon--search",
  "cart": "tvg_header_BIfLoG_cart",
  "cart__count": "tvg_header_BIfLoG_cart__count",
  "cart__sr": "tvg_header_BIfLoG_cart__sr",
  "container": "tvg_header_BIfLoG_container",
  "drawer-extras": "tvg_header_BIfLoG_drawer-extras",
  "drawer-extras__currency": "tvg_header_BIfLoG_drawer-extras__currency",
  "drawer-extras__currency-chevron": "tvg_header_BIfLoG_drawer-extras__currency-chevron",
  "drawer-extras__currency-label": "tvg_header_BIfLoG_drawer-extras__currency-label",
  "drawer-extras__link": "tvg_header_BIfLoG_drawer-extras__link",
  "drawer-extras__markets-wrap": "tvg_header_BIfLoG_drawer-extras__markets-wrap",
  "drawer-triggers": "tvg_header_BIfLoG_drawer-triggers",
  "hamburger": "tvg_header_BIfLoG_hamburger",
  "logo": "tvg_header_BIfLoG_logo",
  "logo__image": "tvg_header_BIfLoG_logo__image",
  "logo__image--dark": "tvg_header_BIfLoG_logo__image--dark",
  "logo__image--light": "tvg_header_BIfLoG_logo__image--light",
  "logo__link": "tvg_header_BIfLoG_logo__link",
  "logo__text": "tvg_header_BIfLoG_logo__text",
  "logo__text--fallback": "tvg_header_BIfLoG_logo__text--fallback",
  "logo__wrapper": "tvg_header_BIfLoG_logo__wrapper",
  "logo__wrapper--swap": "tvg_header_BIfLoG_logo__wrapper--swap",
  "markets": "tvg_header_BIfLoG_markets",
  "markets-wrap": "tvg_header_BIfLoG_markets-wrap",
  "markets__chevron": "tvg_header_BIfLoG_markets__chevron",
  "megamenu-backdrop": "tvg_header_BIfLoG_megamenu-backdrop",
  "menu": "tvg_header_BIfLoG_menu",
  "menu__list": "tvg_header_BIfLoG_menu__list",
  "mobile-drawer-bg": "tvg_header_BIfLoG_mobile-drawer-bg",
  "mobile-drawer-close": "tvg_header_BIfLoG_mobile-drawer-close",
  "mobile-drawer-header": "tvg_header_BIfLoG_mobile-drawer-header",
  "root": "tvg_header_BIfLoG_root",
  "spacer": "tvg_header_BIfLoG_spacer",
  "wrapper": "tvg_header_BIfLoG_wrapper"
} as const
export type ClassNames = keyof typeof style
export default style
