/* DO NOT EDIT: This file is auto-generated and will be overwritten. [build-fingerprint:codegen] */
export const style = {
  "container": "tvg_search_drawer_Z7D_-W_container",
  "content": "tvg_search_drawer_Z7D_-W_content",
  "cta": "tvg_search_drawer_Z7D_-W_cta",
  "cta__wrapper": "tvg_search_drawer_Z7D_-W_cta__wrapper",
  "empty": "tvg_search_drawer_Z7D_-W_empty",
  "form": "tvg_search_drawer_Z7D_-W_form",
  "form__actions": "tvg_search_drawer_Z7D_-W_form__actions",
  "form__clear": "tvg_search_drawer_Z7D_-W_form__clear",
  "form__close": "tvg_search_drawer_Z7D_-W_form__close",
  "form__cluster": "tvg_search_drawer_Z7D_-W_form__cluster",
  "form__field": "tvg_search_drawer_Z7D_-W_form__field",
  "form__icon": "tvg_search_drawer_Z7D_-W_form__icon",
  "form__input": "tvg_search_drawer_Z7D_-W_form__input",
  "form__mirror": "tvg_search_drawer_Z7D_-W_form__mirror",
  "form__wrapper": "tvg_search_drawer_Z7D_-W_form__wrapper",
  "header": "tvg_search_drawer_Z7D_-W_header",
  "logo": "tvg_search_drawer_Z7D_-W_logo",
  "logo__image": "tvg_search_drawer_Z7D_-W_logo__image",
  "logo__link": "tvg_search_drawer_Z7D_-W_logo__link",
  "logo__text": "tvg_search_drawer_Z7D_-W_logo__text",
  "overlay": "tvg_search_drawer_Z7D_-W_overlay",
  "product": "tvg_search_drawer_Z7D_-W_product",
  "products": "tvg_search_drawer_Z7D_-W_products",
  "products__title": "tvg_search_drawer_Z7D_-W_products__title",
  "products__wrapper": "tvg_search_drawer_Z7D_-W_products__wrapper",
  "root": "tvg_search_drawer_Z7D_-W_root",
  "search": "tvg_search_drawer_Z7D_-W_search",
  "suggestion": "tvg_search_drawer_Z7D_-W_suggestion",
  "suggestion__item": "tvg_search_drawer_Z7D_-W_suggestion__item",
  "suggestions": "tvg_search_drawer_Z7D_-W_suggestions",
  "suggestions__initial": "tvg_search_drawer_Z7D_-W_suggestions__initial",
  "suggestions__title": "tvg_search_drawer_Z7D_-W_suggestions__title",
  "suggestions__wrapper": "tvg_search_drawer_Z7D_-W_suggestions__wrapper",
  "wrapper": "tvg_search_drawer_Z7D_-W_wrapper"
} as const
export type ClassNames = keyof typeof style
export default style
