name: 'Deploy to Shopify'
run-name: Deploy to Shopify - ${{ inputs.deployment_target || 'dev-testing' }}

on:
  push:
    branches:
      - devops/deploy-to-shopify
      - main
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Deployment target'
        required: true
        default: 'dev-qa'
        type: choice
        options:
          - dev-qa
          - uat
      content_override_patterns:
        description: 'Content override patterns (use ||| as delimiter). See CI.md'
        required: false
        type: string

jobs:
  matrix-setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-setup.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - id: matrix-setup
        run: |
          matrix=$(bun ./devops/ci/prepare-deployment-matrix.js -f devops/src/config/deployment-matrix.json -t ${{ inputs.deployment_target || 'dev-testing' }})
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  deploy-to-shopify:
    needs: matrix-setup
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix: ${{ fromJSON(needs.matrix-setup.outputs.matrix) }}
    environment:
      name: ${{ matrix.environment.name }}
    concurrency:
      group: 'deploy-to-shopify-${{ matrix.environment.name }}'
      cancel-in-progress: true
    env:
      COMPOSE_BAKE: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      COMPOSE_PROJECT_NAME: 'deploy-to-shopify-${{ matrix.environment.name }}'
      DEPLOYMENT_CONTENT_OVERRIDE_PATTERNS_WORKFLOW_CONFIG: ${{ matrix.environment.content_override_patterns }}
      DEPLOYMENT_CONTENT_OVERRIDE_PATTERNS_DISPATCH: ${{ inputs.content_override_patterns }}
      DEPLOYMENT_INITIAL_CONTENT_SOURCE: ${{ vars.DEPLOYMENT_INITIAL_CONTENT_SOURCE }}
      DEPLOYMENT_TARGET: ${{ inputs.deployment_target || 'dev-testing' }}
      DEVOPS_ACTOR: ${{ github.actor }}
      DOCKER_BUILDKIT: 1
      SHOPIFY_CLI_ADMIN_AUTH_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
      SHOPIFY_CLI_STACKTRACE: 1
      SHOPIFY_CLI_TTY: 0
      SHOPIFY_SHOP: '${{ matrix.environment.name }}.myshopify.com'
    steps:
      - name: 'Checkout everything'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          token: ${{ secrets.CHECKOUT_ACTION_PAT }}

      - name: 'Init git config'
        run: |
          git config --global user.name 'Autobot'
          git config --global user.email 'engineering@vaangroup.com'
        # Workaround for No TTY issue
        shell: 'script -qec "bash {0}"'

      - name: 'Build and start `main_cd` container'
        run: |
          ./devops/ci/start-cd-container.sh
        shell: 'script -qec "bash {0}"'

      - name: 'Prepare deployment branch'
        run: |
          ./devops/ci/run-in-cd-container.sh bb devops-deploy-to-shopify -s prepare
        shell: 'script -qec "bash {0}"'

      - name: 'Push changes'
        # only for the current branch
        run: |
          git push origin HEAD
        shell: 'script -qec "bash {0}"'

      - name: 'Deploy to target'
        run: |
          ./devops/ci/run-in-cd-container.sh bb devops-deploy-to-shopify -s populate
        shell: 'script -qec "bash {0}"'

      - name: 'Push changes'
        run: |
          git push origin HEAD
        shell: 'script -qec "bash {0}"'

      - name: 'Shutdown containers'
        run: |
          ./devops/ci/shutdown-cd-container.sh
        shell: 'script -qec "bash {0}"'
